[logger]
path = "/var/log/"   # 日志文件路径。默认为空，表示关闭，仅输出到终端
file = "{Y-m-d}.log" # 日志文件格式。默认为"{Y-m-d}.log"
prefix = ""            # 日志内容输出前缀。默认为空
level = "all"         # 日志输出级别
ctxKeys = []            # Context上下文变量名称，自动打印Context的变量到日志中。默认为空
headerPrint = true          # 是否打印日志的头信息。默认true
stdoutPrint = true          # 日志是否同时输出到终端。默认true
rotateSize = 0             # 按照日志文件大小对文件进行滚动切分。默认为0，表示关闭滚动切分特性
rotateExpire = 0             # 按照日志文件时间间隔对文件滚动切分。默认为0，表示关闭滚动切分特性
rotateBackupLimit = 0             # 按照切分的文件数量清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
rotateBackupExpire = 0             # 按照切分的文件有效期清理切分文件，当滚动切分特性开启时有效。默认为0，表示不备份，切分则删除
rotateBackupCompress = 0             # 滚动切分文件的压缩比（0-9）。默认为0，表示不压缩
rotateCheckInterval = "1h"          # 滚动切分的时间检测间隔，一般不需要设置。默认为1小时

# HTTP Server
[server]
Address = ":5555"
ServerAgent = "g-emqx-user-manager"

# 数据库配置
[database]
[[database.default]]
Host = "192.168.20.100"
Port = "5432"
User = "postgres"
Pass = "123456"
Name = "emqx"
Type = "pgsql"
Role = "master"
Weight = 100
Debug = true
charset = "utf8"
priority = "1"

# Redis数据库配置
[redis]
default = "192.168.20.100:6379,1"

[emqx]
default = "http://192.168.20.100:18083/api/v5"
tableName = "mqtt_user"